//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("GameDBModel", "FK__Moves__Id__37A5467C", "Games", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(krestiki_noliki.Games), "Moves", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(krestiki_noliki.Moves), true)]

#endregion

namespace krestiki_noliki
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class GameDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new GameDBEntities object using the connection string found in the 'GameDBEntities' section of the application configuration file.
        /// </summary>
        public GameDBEntities() : base("name=GameDBEntities", "GameDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GameDBEntities object.
        /// </summary>
        public GameDBEntities(string connectionString) : base(connectionString, "GameDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GameDBEntities object.
        /// </summary>
        public GameDBEntities(EntityConnection connection) : base(connection, "GameDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Games> Games
        {
            get
            {
                if ((_Games == null))
                {
                    _Games = base.CreateObjectSet<Games>("Games");
                }
                return _Games;
            }
        }
        private ObjectSet<Games> _Games;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Moves> Moves
        {
            get
            {
                if ((_Moves == null))
                {
                    _Moves = base.CreateObjectSet<Moves>("Moves");
                }
                return _Moves;
            }
        }
        private ObjectSet<Moves> _Moves;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Games EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGames(Games games)
        {
            base.AddObject("Games", games);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Moves EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMoves(Moves moves)
        {
            base.AddObject("Moves", moves);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GameDBModel", Name="Games")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Games : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Games object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="firstMove">Initial value of the FirstMove property.</param>
        /// <param name="winner">Initial value of the Winner property.</param>
        /// <param name="winX">Initial value of the WinX property.</param>
        /// <param name="winY">Initial value of the WinY property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        public static Games CreateGames(global::System.Guid id, global::System.Int32 firstMove, global::System.Int32 winner, global::System.Int32 winX, global::System.Int32 winY, global::System.DateTime date)
        {
            Games games = new Games();
            games.Id = id;
            games.FirstMove = firstMove;
            games.Winner = winner;
            games.WinX = winX;
            games.WinY = winY;
            games.Date = date;
            return games;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FirstMove
        {
            get
            {
                return _FirstMove;
            }
            set
            {
                OnFirstMoveChanging(value);
                ReportPropertyChanging("FirstMove");
                _FirstMove = StructuralObject.SetValidValue(value, "FirstMove");
                ReportPropertyChanged("FirstMove");
                OnFirstMoveChanged();
            }
        }
        private global::System.Int32 _FirstMove;
        partial void OnFirstMoveChanging(global::System.Int32 value);
        partial void OnFirstMoveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Winner
        {
            get
            {
                return _Winner;
            }
            set
            {
                OnWinnerChanging(value);
                ReportPropertyChanging("Winner");
                _Winner = StructuralObject.SetValidValue(value, "Winner");
                ReportPropertyChanged("Winner");
                OnWinnerChanged();
            }
        }
        private global::System.Int32 _Winner;
        partial void OnWinnerChanging(global::System.Int32 value);
        partial void OnWinnerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WinX
        {
            get
            {
                return _WinX;
            }
            set
            {
                OnWinXChanging(value);
                ReportPropertyChanging("WinX");
                _WinX = StructuralObject.SetValidValue(value, "WinX");
                ReportPropertyChanged("WinX");
                OnWinXChanged();
            }
        }
        private global::System.Int32 _WinX;
        partial void OnWinXChanging(global::System.Int32 value);
        partial void OnWinXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WinY
        {
            get
            {
                return _WinY;
            }
            set
            {
                OnWinYChanging(value);
                ReportPropertyChanging("WinY");
                _WinY = StructuralObject.SetValidValue(value, "WinY");
                ReportPropertyChanged("WinY");
                OnWinYChanged();
            }
        }
        private global::System.Int32 _WinY;
        partial void OnWinYChanging(global::System.Int32 value);
        partial void OnWinYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value, "Date");
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GameDBModel", "FK__Moves__Id__37A5467C", "Moves")]
        public EntityCollection<Moves> Moves
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Moves>("GameDBModel.FK__Moves__Id__37A5467C", "Moves");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Moves>("GameDBModel.FK__Moves__Id__37A5467C", "Moves", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GameDBModel", Name="Moves")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Moves : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Moves object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="moveId">Initial value of the MoveId property.</param>
        /// <param name="x">Initial value of the X property.</param>
        /// <param name="y">Initial value of the Y property.</param>
        public static Moves CreateMoves(global::System.Guid id, global::System.Int32 moveId, global::System.Int32 x, global::System.Int32 y)
        {
            Moves moves = new Moves();
            moves.Id = id;
            moves.MoveId = moveId;
            moves.X = x;
            moves.Y = y;
            return moves;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MoveId
        {
            get
            {
                return _MoveId;
            }
            set
            {
                if (_MoveId != value)
                {
                    OnMoveIdChanging(value);
                    ReportPropertyChanging("MoveId");
                    _MoveId = StructuralObject.SetValidValue(value, "MoveId");
                    ReportPropertyChanged("MoveId");
                    OnMoveIdChanged();
                }
            }
        }
        private global::System.Int32 _MoveId;
        partial void OnMoveIdChanging(global::System.Int32 value);
        partial void OnMoveIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 X
        {
            get
            {
                return _X;
            }
            set
            {
                if (_X != value)
                {
                    OnXChanging(value);
                    ReportPropertyChanging("X");
                    _X = StructuralObject.SetValidValue(value, "X");
                    ReportPropertyChanged("X");
                    OnXChanged();
                }
            }
        }
        private global::System.Int32 _X;
        partial void OnXChanging(global::System.Int32 value);
        partial void OnXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Y
        {
            get
            {
                return _Y;
            }
            set
            {
                if (_Y != value)
                {
                    OnYChanging(value);
                    ReportPropertyChanging("Y");
                    _Y = StructuralObject.SetValidValue(value, "Y");
                    ReportPropertyChanged("Y");
                    OnYChanged();
                }
            }
        }
        private global::System.Int32 _Y;
        partial void OnYChanging(global::System.Int32 value);
        partial void OnYChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GameDBModel", "FK__Moves__Id__37A5467C", "Games")]
        public Games Games
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Games>("GameDBModel.FK__Moves__Id__37A5467C", "Games").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Games>("GameDBModel.FK__Moves__Id__37A5467C", "Games").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Games> GamesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Games>("GameDBModel.FK__Moves__Id__37A5467C", "Games");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Games>("GameDBModel.FK__Moves__Id__37A5467C", "Games", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
