//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace krestiki_noliki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moves
    {
        public System.Guid Id { get; set; }
        public int MoveId { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
    
        public virtual Games Games { get; set; }
    }
}